import Link from "next/link";
import { ArrowRight, CalendarDays, Layers3, Sparkles, TimerReset } from "lucide-react";
import { Sidebar } from "@/components/sidebar";
import { demoItems } from "@/lib/demo-data";

export default function Dashboard() {
  const ready = demoItems.filter((item) => item.status === "ready").length;
  const draft = demoItems.filter((item) => item.status === "draft").length;

  return <div className="app-shell"><Sidebar/><main className="main-content"><header className="page-header"><div><span className="eyebrow accent">AUGUST CONTENT</span><h1>Your month, already mapped.</h1><p>Build the strategy first. Generate only the assets you actually need.</p></div><Link href="/onboarding" className="button primary"><Sparkles size={16}/> Build next month</Link></header><section className="metric-grid"><div className="metric-card"><CalendarDays size={20}/><span>Plan</span><strong>30 days</strong><small>3 platforms</small></div><div className="metric-card"><Layers3 size={20}/><span>Content status</span><strong>{ready} ready</strong><small>{draft} drafts in progress</small></div><div className="metric-card"><TimerReset size={20}/><span>Publishing cadence</span><strong>5 / week</strong><small>Adjust anytime in your plan</small></div></section><section className="panel split-panel"><div><span className="eyebrow">THIS MONTH'S STRATEGY</span><h2>Teach the process before selling the fix.</h2><p>The current mix builds recognition first, then authority, then direct offers. Each idea can be adapted for Facebook, Instagram, or LinkedIn without starting from scratch.</p><Link href="/calendar" className="text-link">Open full 30-day plan <ArrowRight size={15}/></Link></div><div className="mix-list">{[["Education","40%"],["Authority","20%"],["Story","15%"],["Conversation","15%"],["Offer","10%"]].map(([name,pct]) => <div key={name}><span>{name}</span><strong>{pct}</strong><i style={{width:pct}} /></div>)}</div></section><section className="section-heading"><div><span className="eyebrow">NEXT UP</span><h2>Ready to finish</h2></div><Link href="/calendar" className="text-link">View calendar <ArrowRight size={15}/></Link></section><div className="preview-list">{demoItems.slice(0,4).map(item => <Link href={`/content/${item.id}`} className="preview-row" key={item.id}><span className="preview-day">DAY {item.day}</span><div><strong>{item.title}</strong><small>{item.pillar} · {item.format}</small></div><span className="platform-chip">{item.platforms.join(" + ")}</span><ArrowRight size={16}/></Link>)}</div></main></div>;
}
