import Link from "next/link";
import { ArrowLeft, Copy, ImageIcon, RefreshCcw, WandSparkles } from "lucide-react";
import { Sidebar } from "@/components/sidebar";
import { demoItems } from "@/lib/demo-data";

export default async function ContentPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params;
  const item = demoItems.find((entry) => entry.id === id) ?? demoItems[0];

  return <div className="app-shell"><Sidebar/><main className="main-content editor-page"><Link href="/calendar" className="back-link"><ArrowLeft size={15}/> Back to calendar</Link><header className="editor-header"><div><span className="eyebrow accent">DAY {item.day} · {item.pillar}</span><h1>{item.title}</h1><div className="platform-row large">{item.platforms.map(p => <span key={p}>{p}</span>)}</div></div><span className={`status status-${item.status}`}>{item.status}</span></header><div className="editor-grid"><div className="editor-main"><section className="panel content-section"><div className="content-label">HOOK</div><p className="hook-copy">{item.hook}</p><button className="ghost-action"><RefreshCcw size={14}/> Rewrite hook</button></section><section className="panel content-section"><div className="content-label">CAPTION</div><p className="caption-copy">{item.caption}</p><div className="action-row"><button className="button secondary"><Copy size={15}/> Copy caption</button><button className="button secondary"><WandSparkles size={15}/> Rewrite</button></div></section><section className="panel content-section"><div className="content-label">CTA</div><p>{item.cta}</p><button className="ghost-action"><RefreshCcw size={14}/> Change CTA</button></section></div><aside className="editor-side"><section className="panel side-card"><div className="content-label">IMAGE DIRECTION</div><p>{item.imageConcept}</p><div className="image-placeholder"><ImageIcon size={24}/><span>Generate only when needed</span></div><button className="button primary full"><ImageIcon size={15}/> Generate image</button><button className="button secondary full"><Copy size={15}/> Copy image prompt</button></section><section className="panel side-card"><div className="content-label">ALT TEXT</div><p>{item.altText}</p><button className="ghost-action"><Copy size={14}/> Copy alt text</button></section><section className="panel side-card"><div className="content-label">REPURPOSE</div><div className="repurpose-grid"><button>Facebook</button><button>Instagram</button><button>LinkedIn</button><button>Reel script</button><button>Carousel</button><button>Email</button></div></section></aside></div></main></div>;
}
